In [1]:
#2.1 사칙 연산 20152534 최종헌
1+2

3

In [2]:
(1+2*3-4)/5

0.6

In [3]:
2**8

256

In [4]:
#2.2 변수
x=1
y=1/3
x+y

1.3333333333333333

In [5]:
Data_1=1/5
Data_2=3/5
Data_1+Data_2

0.8

In [8]:
#2.3 자료형
type(100)

int

In [9]:
type(100.1)

float

In [10]:
x=100
type(x)

int

In [11]:
x=100.1
type(x)

float

In [13]:
x='learning'
type(x)

str

In [14]:
#2.4 print문
x=1/3
x
y=2/3
y

0.6666666666666666

In [15]:
x=1/3
print(x)
y=2/3
print(y)

0.3333333333333333
0.6666666666666666


In [18]:
print('x= '+str(x))

x= 0.3333333333333333


In [20]:
print('weight={0}kg'.format(x))

weight=0.3333333333333333kg


In [21]:
x=1/3
y=1/7
z=1/4
print('weight:{0}kg {1}kg {2}kg'.format(x,y,z))

weight:0.3333333333333333kg 0.14285714285714285kg 0.25kg


In [22]:
print('weight:{0:.2f}kg {1:.2f}kg {2:.2f}kg'.format(x,y,z))

weight:0.33kg 0.14kg 0.25kg


In [23]:
#2.5 list
x=[1,1,2,3,5]
print(x)

[1, 1, 2, 3, 5]


In [24]:
x[0]

1

In [25]:
x[2]

2

In [26]:
print(type(x))

<class 'list'>


In [27]:
print(type(x[0]))

<class 'int'>


In [28]:
s=['SUN',1,'MON',2]
print(type(s[0]))
print(type(s[1]))

<class 'str'>
<class 'int'>


In [29]:
a=[[1,2,3],[4,5,6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [30]:
print(a[0][1])

2


In [31]:
x=[1,1,2,3,5]
x[3]=100
print(x)

[1, 1, 2, 100, 5]


In [33]:
x=[1,1,2,3,5]
len(x)

5

In [34]:
y=range(5,10)
print(y[0],y[1],y[2],y[3],y[4])

5 6 7 8 9


In [35]:
print(y)

range(5, 10)


In [36]:
z=list(range(5,10))
print(z)

[5, 6, 7, 8, 9]


In [37]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [38]:
#2.6 tuple
a=(1,2,3)
print(a)


(1, 2, 3)


In [39]:
a[1]

2

In [40]:
type(a)

tuple

In [41]:
a=(1)

In [42]:
type(a)

int

In [43]:
a=(1,)
type(a)

tuple

In [44]:
#2.7 if문
x=11
if x>10:
    print('x is')
    print('       larger than 10.')
else:
    print('x is smaller than 11')

x is
       larger than 10.


In [45]:
x>10

True

In [46]:
type(x>10)

bool

In [47]:
x=15
if 10<=x and x<=20:
    print('x is between 10 and 20')

x is between 10 and 20


In [48]:
#2.8 for문
for i in [1,2,3]:
    print(i)

1
2
3


In [51]:
num=[2,4,6,8,10]
for i in range(len(num)):
    num[i]=num[i]*2
print(num)

[4, 8, 12, 16, 20]


In [52]:
#2.9 벡터
[1,2]+[3,4]

[1, 2, 3, 4]

In [3]:
import numpy as np #넘파이 이용

In [54]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [55]:
print(x)

[1 2 3]


In [56]:
y=np.array([4,5,6])
print(x+y)

[5 7 9]


In [57]:
type(x)

numpy.ndarray

In [58]:
x[0]

1

In [59]:
x[0]=100

In [60]:
print(x)

[100   2   3]


In [62]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [63]:
print(np.arange(5,10))

[5 6 7 8 9]


In [65]:
a=np.array([1,1])
b=a
print('a = '+str(a))
print('b = '+str(b))
b[0]=100
print('b = '+str(b))
print('a = '+str(a))

a = [1 1]
b = [1 1]
b = [100   1]
a = [100   1]


In [66]:
a=np.array([1,1])
b=a.copy()
print('a = '+str(a))
print('b = '+str(b))
b[0]=100
print('b = '+str(b)) #b는 a와 관계없이 독립된 변수
print('a = '+str(a))

a = [1 1]
b = [1 1]
b = [100   1]
a = [1 1]


In [67]:
#2.10 행렬
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [68]:
x=np.array([[1,2,3],[4,5,6]])
x.shape #배열 크기

(2, 3)

In [69]:
w,h=x.shape
print(w)
print(h)

2
3


In [70]:
type(x.shape)

tuple

In [71]:
x=np.array([[1,2,3],[4,5,6]])
x[1,2]

6

In [72]:
#요소 수정
x=np.array([[1,2,3],[4,5,6]])
x[1,2]=100
print(x)

[[  1   2   3]
 [  4   5 100]]


In [75]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [77]:
print(np.zeros((2,10))) #2x10 행렬

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [78]:
print(np.ones((2,10))) #1로 가득한 2x10행렬

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [79]:
np.random.rand(2,3) #2x3난수 행렬

array([[0.92127229, 0.28929882, 0.51133714],
       [0.14984153, 0.01183589, 0.72149709]])

In [80]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [81]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
#2.11행렬의 사칙연산
x=np.array([[4,4,4],[8,8,8]])
y=np.array([[1,1,1],[2,2,2]])
print(x+y)

[[ 5  5  5]
 [10 10 10]]


In [83]:
x=np.array([[4,4,4],[8,8,8]])
print(10*x)#행렬의 실수배

[[40 40 40]
 [80 80 80]]


In [86]:
x=np.array([[4,4,4],[8,8,8]])
print(np.exp(x))#산술함수

[[  54.59815003   54.59815003   54.59815003]
 [2980.95798704 2980.95798704 2980.95798704]]


In [88]:
#np.sqrt(x)는 제곱근 np.log(x)로그 np.round(x) 반올림, np.mean(x)평균, np.std(x) 표준편차, np.max(x)/min(x) 최대 최소
v=np.array([[1,2,3],[4,5,6]])
w=np.array([[1,1],[2,2],[3,3]])
print(v.dot(w)) #4장에서 자세히

[[14 14]
 [32 32]]


In [89]:
#2.12 슬라이싱
x=np.arange(10)
print(x)
print(x[:5]) #5 이전까지 출력

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [90]:
print(x[5:])

[5 6 7 8 9]


In [91]:
print(x[3:8])

[3 4 5 6 7]


In [92]:
print(x[3:8:2])#공차 2

[3 5 7]


In [93]:
print(x[::-1]) #배열 순서 반대로

[9 8 7 6 5 4 3 2 1 0]


In [94]:
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)
print(y[:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]]


In [95]:
#2.13조건을 만족하는 데이터 수정
#bool true false사용
x=np.array([1,1,2,3,5,8,13])
x>3

array([False, False, False, False,  True,  True,  True])

In [96]:
x[x>3]

array([ 5,  8, 13])

In [97]:
x[x>3]=999
print(x)

[  1   1   2   3 999 999 999]


In [98]:
#2.14 help: help(함수명)= 함수 설명확인
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above fo

In [99]:
#2.15함수
def my_func1():
    print("HI!")
my_func1()

HI!


In [101]:
def my_func2(a,b):
    c=a+b
    return c
my_func2(1,2)

3

In [102]:
def my_func3(D):
    m=np.mean(D)
    s=np.std(D)
    return m,s

In [105]:
data=np.random.randn(100)
data_mean,data_std=my_func3(data)
print('mean:{0:3.2f},std:{1:3.2f}'.format(data_mean,data_std)) #값이 계속 다르게 출력된다. 난수라

mean:-0.03,std:1.02


In [106]:
output=my_func3(data)
print(output)
print(type(output))
print('mean:{0:3.2f},std:{1:3.2f}'.format(output[0],output[1]))

(-0.027009419239670752, 1.0211241132651991)
<class 'tuple'>
mean:-0.03,std:1.02


In [109]:
#2.16파일 저장
data=np.random.randn(5)
print(data)
np.save('datafile.npy',data) #세이브
data=[] #데이터 삭제
print(data)
data=np.load('datafile.npy')#로드
print(data)#결과는 또 때마다 다르다.

[-0.31237116  0.73310832  0.42770645  1.40789291  0.49226685]
[]
[-0.31237116  0.73310832  0.42770645  1.40789291  0.49226685]


In [4]:
data1=np.array([1,2,3])
data2=np.array([10,20,30])
np.savez('datafile2.npz',data1=data1,data2=data2) #세이브
data1=[]#data삭제
data2=[]
outfile=np.load('datafile2.npz')#로드
print(outfile.files)
data1=outfile['data1']
data2=outfile['data2']
print(data1)
print(data2)

['data1', 'data2']
[1 2 3]
[10 20 30]
